#
# メインコンテナ
#
version: '2'
services:
  server:
    build: .
    # image: gendosu/ubuntu-consul
    command: consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -node=agent-one -config-dir /etc/consul.d

  server2:
    build: .
    # image: gendosu/ubuntu-consul
    links:
      - server
    command: consul agent -server -data-dir /tmp/consul -config-dir /etc/consul.d -join server

  client1:
    build:
      context: .
      dockerfile: Dockerfile-client
    # image: gendosu/ubuntu-consul
    links:
      - server
    command: /usr/bin/supervisord -n

  client2:
    build:
      context: .
      dockerfile: Dockerfile-client
    # image: gendosu/ubuntu-consul
    links:
      - server
    command: /usr/bin/supervisord -n
